"""initial tables

Revision ID: 1b1a91b914ce
Revises: 
Create Date: 2026-09-29 13:19:58.156032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1a91b914ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'PSYCHOLOGIST', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_session_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ai_session_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('recommendations_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_session_id')
    )
    op.create_table('psychologists',
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('mock_slots', sa.JSON(), nullable=True),
    sa.Column('certificates', sa.JSON(), nullable=True),
    sa.Column('bio', sa.JSON(), nullable=False),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('methods', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('meet_link', sa.String(length=255), nullable=True),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profile_status', sa.Enum('ACTIVE', 'FROZEN', 'PENDING_MODERATION', name='psychologist_status'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('psychologist_id')
    )
    op.create_table('ai_session_symptom_codes',
    sa.Column('ai_session_log_id', sa.Uuid(), nullable=False),
    sa.Column('symptom_code', sa.Enum('ANXIETY', 'BURNOUT', 'RELATIONSHIP', 'STRESS', 'GRIEF', 'SELF_ESTEEM', 'LOW_MOOD', 'SLEEP', 'FAMILY', 'ANGER', 'TRAUMA', 'ADDICTION', 'EATING', 'LONELINESS', 'IDENTITY', 'WORK_CAREER', 'MOTIVATION', name='symptom_code'), nullable=False),
    sa.ForeignKeyConstraint(['ai_session_log_id'], ['ai_session_logs.id'], ),
    sa.PrimaryKeyConstraint('ai_session_log_id', 'symptom_code')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('selected_time', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'CANCELLED', 'COMPLETED', name='booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'HELD', 'PAID', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=False),
    sa.Column('selection_source', sa.Enum('AI_RECOMMENDATION', 'MANUAL_FILTER', name='selection_source'), nullable=False),
    sa.Column('ai_session_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ai_session_id'], ['ai_session_logs.ai_session_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_session_id')
    )
    op.create_table('psychologist_specializations',
    sa.Column('psychologist_id', sa.Uuid(), nullable=False),
    sa.Column('symptom_code', sa.Enum('ANXIETY', 'BURNOUT', 'RELATIONSHIP', 'STRESS', 'GRIEF', 'SELF_ESTEEM', 'LOW_MOOD', 'SLEEP', 'FAMILY', 'ANGER', 'TRAUMA', 'ADDICTION', 'EATING', 'LONELINESS', 'IDENTITY', 'WORK_CAREER', 'MOTIVATION', name='symptom_code'), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('psychologist_id', 'symptom_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psychologist_specializations')
    op.drop_table('bookings')
    op.drop_table('ai_session_symptom_codes')
    op.drop_table('psychologists')
    op.drop_table('ai_session_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
