"""add booking indexes and slot uniqueness

Revision ID: 8d54b7c51f06
Revises: 0ca415b21a41
Create Date: 2026-10-06 18:36:52.758060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d54b7c51f06'
down_revision: Union[str, Sequence[str], None] = '0ca415b21a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('selected_time_label', sa.String(length=100), nullable=False))
    op.alter_column(
        'bookings', 'selected_time',
        existing_type=sa.VARCHAR(length=100),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="selected_time::timestamptz",
    )
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_psychologist_id'), 'bookings', ['psychologist_id'], unique=False)
    op.create_index('uq_booking_confirmed_slot', 'bookings', ['psychologist_id', 'selected_time'], unique=True, postgresql_where=sa.text("status = 'CONFIRMED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_booking_confirmed_slot', table_name='bookings', postgresql_where=sa.text("status = 'CONFIRMED'"))
    op.drop_index(op.f('ix_bookings_psychologist_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.alter_column(
        'bookings', 'selected_time',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
        postgresql_using="selected_time::text",
    )
    op.drop_column('bookings', 'selected_time_label')
    # ### end Alembic commands ###
